"""App-original motion-graphics submission handling (James DeFleur's piece 3 contract).

Hermes (the author) submits a project-local HTML/SVG/GSAP composition plus a
visual plan; this module validates paths, sizes, file kinds and the plan, stores
the composition under <project>/motion/src, and computes a tree hash so a
capture proof is bound to the exact composition the final render uses.

Contract (James' defleur-motion SKILL.md and references/motion-contract.md):
index.html exposes window.renderFrame(t) (synchronous state reconstruction),
the #live element, window.sourceFrameForOutputFrame(frame) (provided by
defleur/ledger.js, generated by the app), optional window.visualMode(t) and
window.captionSuppressed(t). visual-plan beats carry start/end, spoken_anchor,
viewer_inference, visual_family, state_before, state_after, causal_action,
caption_treatment (show|suppress) and speaker_return.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
import os
import shutil
from pathlib import Path

from editing import Rejected

TEXT_KINDS = {".html", ".css", ".js", ".svg", ".json"}
BINARY_KINDS = {".png", ".jpg", ".jpeg", ".webp", ".woff2", ".mp4"}
MAGIC = {".png": lambda b: b[:8] == b"\x89PNG\r\n\x1a\n", ".jpg": lambda b: b[:3] == b"\xff\xd8\xff",
         ".jpeg": lambda b: b[:3] == b"\xff\xd8\xff", ".webp": lambda b: b[:4] == b"RIFF" and b[8:12] == b"WEBP",
         ".woff2": lambda b: b[:4] == b"wOF2", ".mp4": lambda b: b[4:8] == b"ftyp"}
PATH = re.compile(r"^[a-z0-9][a-z0-9_-]{0,47}(\.[a-z0-9]{1,5})?(/[a-z0-9][a-z0-9_-]{0,47}(\.[a-z0-9]{1,5})?){0,2}$")
RESERVED = ("defleur/", "base_frames/", "picture-frames/", "proof-raw/", "node_modules/")
RESERVED_FILES = {"locked-timeline.json", "visual-plan.json", "crop-ledger.json", "package.json", "capture-smoke.json",
                  "capture-proof.json", "capture-full.json", "caption-style.json"}
MAX_FILES = 200
MAX_TEXT_FILE = 2 * 1024 * 1024
MAX_INLINE_TOTAL = 3 * 1024 * 1024
MAX_ASSET = {".png": 32 << 20, ".jpg": 32 << 20, ".jpeg": 32 << 20, ".webp": 32 << 20, ".woff2": 8 << 20, ".mp4": 2 << 30}
MAX_TREE = 4 << 30
BEAT_FIELDS = ("spoken_anchor", "viewer_inference", "visual_family", "state_before", "state_after", "causal_action",
               "caption_treatment", "speaker_return")
INSERT_BASE = 10_000_000   # base-frame ids at or above this are insert media, not source frames
INSERT_STRIDE = 1_000_000


def src_dir(project: Path) -> Path:
    return project / "motion" / "src"


def check_path(rel: str) -> str:
    if not isinstance(rel, str) or not PATH.fullmatch(rel) or ".." in rel:
        raise Rejected(f"motion file path {rel!r} not allowed: lowercase a-z 0-9 _ - names, up to 3 levels, one extension")
    if rel.startswith(RESERVED) or rel in RESERVED_FILES:
        raise Rejected(f"motion file path {rel!r} is reserved for the app (defleur/, base_frames/, timeline and capture files)")
    ext = Path(rel).suffix
    if ext not in TEXT_KINDS | BINARY_KINDS:
        raise Rejected(f"motion file {rel!r}: allowed kinds are {sorted(TEXT_KINDS | BINARY_KINDS)}")
    return rel


def check_bytes(rel: str, data: bytes) -> None:
    ext = Path(rel).suffix
    if ext in TEXT_KINDS:
        if len(data) > MAX_TEXT_FILE:
            raise Rejected(f"{rel}: text files are limited to {MAX_TEXT_FILE // 1024} KiB")
        try:
            data.decode("utf-8")
        except UnicodeDecodeError:
            raise Rejected(f"{rel}: text files must be UTF-8") from None
        return
    if len(data) > MAX_ASSET[ext]:
        raise Rejected(f"{rel}: {ext} files are limited to {MAX_ASSET[ext] >> 20} MiB")
    if not MAGIC[ext](data[:16]):
        raise Rejected(f"{rel}: content is not a real {ext} file")


def tree(project: Path) -> list[dict]:
    root = src_dir(project)
    rows = []
    if root.is_dir():
        for p in sorted(root.rglob("*")):
            if p.is_symlink():
                raise Rejected("symlink in motion tree")
            if p.is_file():
                h = hashlib.sha256()
                with p.open("rb") as f:
                    for chunk in iter(lambda: f.read(1 << 20), b""):
                        h.update(chunk)
                rows.append({"path": p.relative_to(root).as_posix(), "bytes": p.stat().st_size, "sha256": h.hexdigest()})
    return rows


def tree_hash(rows: list[dict], plan: dict) -> str:
    h = hashlib.sha256()
    for r in rows:
        h.update(f"{r['path']}\0{r['sha256']}\n".encode())
    h.update(json.dumps(plan, sort_keys=True).encode())
    return h.hexdigest()


def _num(v, label):
    if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v < 0:
        raise Rejected(f"{label} must be a nonnegative number of seconds")
    return float(v)


def _text(v, label, n=600):
    if not isinstance(v, str) or not v.strip() or len(v) > n:
        raise Rejected(f"{label} must be a nonempty string up to {n} characters")
    return v


def validate_plan(plan, duration: float | None, files: set[str]) -> dict:
    """James' visual-plan.json shape plus the app's 'inserts' (fullscreen B-roll windows through #live)."""
    if not isinstance(plan, dict) or set(plan) - {"beats", "caption_suppress", "inserts", "notes"}:
        raise Rejected("plan must be an object with beats, optional caption_suppress, inserts, notes")
    beats = plan.get("beats")
    if not isinstance(beats, list) or not 1 <= len(beats) <= 200:
        raise Rejected("plan.beats must list 1..200 beats (James' contract: every beat is an explanatory change)")
    last = 0.0
    for i, b in enumerate(beats):
        if not isinstance(b, dict) or set(b) - {"start", "end", *BEAT_FIELDS, "id", "notes"}:
            raise Rejected(f"beat {i}: allowed keys are start, end, {', '.join(BEAT_FIELDS)}, id, notes")
        s, e = _num(b.get("start"), f"beat {i} start"), _num(b.get("end"), f"beat {i} end")
        if not last <= s < e or (duration is not None and e > duration + 1e-6):
            raise Rejected(f"beat {i}: beats must be ordered, non-overlapping and inside the edited timeline ({duration} s)")
        for k in BEAT_FIELDS:
            _text(b.get(k), f"beat {i} {k}")
        if b["caption_treatment"] not in ("show", "suppress"):
            raise Rejected(f"beat {i}: caption_treatment must be 'show' or 'suppress'")
        last = e
    sup = plan.get("caption_suppress", [])
    if not isinstance(sup, list) or len(sup) > 200:
        raise Rejected("plan.caption_suppress must be a list")
    for i, r in enumerate(sup):
        if not isinstance(r, dict) or set(r) - {"start", "end", "reason"}:
            raise Rejected(f"caption_suppress {i}: keys start, end, reason")
        s, e = _num(r.get("start"), "suppress start"), _num(r.get("end"), "suppress end")
        _text(r.get("reason"), f"caption_suppress {i} reason")
        if not any(b["caption_treatment"] == "suppress" and b["start"] <= s < e <= b["end"] for b in beats):
            raise Rejected(f"caption_suppress {i} must sit inside a beat whose caption_treatment is 'suppress' (James' encode.py rule)")
    ins = plan.get("inserts", [])
    if not isinstance(ins, list) or len(ins) > 50:
        raise Rejected("plan.inserts must be a list of up to 50 fullscreen insert windows")
    last = 0.0
    for i, r in enumerate(ins):
        if not isinstance(r, dict) or set(r) - {"start", "end", "asset", "fit", "clip_start_s", "reason"}:
            raise Rejected(f"insert {i}: keys start, end, asset, fit (cover|contain), clip_start_s, reason")
        s, e = _num(r.get("start"), f"insert {i} start"), _num(r.get("end"), f"insert {i} end")
        if not last <= s < e or (duration is not None and e > duration + 1e-6):
            raise Rejected(f"insert {i}: inserts must be ordered, non-overlapping and inside the edited timeline")
        last = e
        _text(r.get("reason"), f"insert {i} reason")
        a = r.get("asset")
        if a not in files or Path(a).suffix not in {".png", ".jpg", ".jpeg", ".webp", ".mp4"}:
            raise Rejected(f"insert {i}: asset must be an uploaded .png/.jpg/.webp/.mp4 in this composition (have: {sorted(files)[:20]})")
        if r.get("fit", "cover") not in ("cover", "contain"):
            raise Rejected(f"insert {i}: fit must be cover or contain")
        _num(r.get("clip_start_s", 0), f"insert {i} clip_start_s")
    return plan


def check_index(text: str) -> None:
    need = {"defleur/ledger.js": "include <script src=\"defleur/ledger.js\"></script> (defines sourceFrameForOutputFrame)",
            "renderFrame": "define window.renderFrame = (t) => {...}", 'id="live"': "have an <img id=\"live\"> element (live footage)"}
    low = text.replace("'", '"')
    missing = [msg for key, msg in need.items() if key not in low]
    if missing:
        raise Rejected("index.html must " + "; ".join(missing))
    if re.search(r"""(src|href)\s*=\s*["']\s*(https?:)?//""", text, re.I) or "@import url(http" in text:
        raise Rejected("index.html references a remote URL; vendor every asset into the composition (GSAP: defleur/gsap.min.js)")


def submit(project: Path, files, plan, duration: float, replace: bool = True) -> dict:
    """Write inline files (text, or {'base64': ...} for small binaries) and the plan. Uploaded assets stay unless replaced."""
    import base64
    if not isinstance(files, dict) or len(files) > MAX_FILES:
        raise Rejected(f"files must be an object of up to {MAX_FILES} path -> content entries")
    decoded, total = {}, 0
    for rel, value in files.items():
        check_path(rel)
        if isinstance(value, str):
            if Path(rel).suffix not in TEXT_KINDS:
                raise Rejected(f"{rel}: binary files need {{'base64': ...}} or create_asset_upload")
            data = value.encode()
        elif isinstance(value, dict) and set(value) == {"base64"} and isinstance(value["base64"], str):
            try:
                data = base64.b64decode(value["base64"], validate=True)
            except ValueError:
                raise Rejected(f"{rel}: invalid base64") from None
        else:
            raise Rejected(f"{rel}: value must be text or {{'base64': '...'}}")
        check_bytes(rel, data)
        total += len(data)
        decoded[rel] = data
    if total > MAX_INLINE_TOTAL:
        raise Rejected("inline files exceed 3 MiB; upload large media with create_asset_upload")
    root = src_dir(project)
    existing = {r["path"] for r in tree(project)}
    keep = existing if not replace else {p for p in existing if Path(p).suffix in BINARY_KINDS and p not in decoded}
    index = decoded.get("index.html")
    if index is None and "index.html" not in keep | existing:
        raise Rejected("the composition needs index.html")
    if index is not None:
        check_index(index.decode())
    validate_plan(plan, duration, set(decoded) | keep)
    staging = project / "motion" / "src.new"
    shutil.rmtree(staging, ignore_errors=True)
    staging.mkdir(parents=True, mode=0o700)
    for rel in keep:
        (staging / rel).parent.mkdir(parents=True, exist_ok=True)
        try:
            (root / rel).rename(staging / rel)
        except OSError:
            shutil.copyfile(root / rel, staging / rel)
    for rel, data in decoded.items():
        (staging / rel).parent.mkdir(parents=True, exist_ok=True)
        (staging / rel).write_bytes(data)
    if not (staging / "index.html").is_file():
        shutil.rmtree(staging)
        raise Rejected("the composition needs index.html")
    shutil.rmtree(root, ignore_errors=True)
    staging.rename(root)
    (project / "motion" / "plan.json").write_text(json.dumps(plan, indent=2))
    return status(project)


def store_asset(project: Path, rel: str, stream, length: int) -> dict:
    check_path(rel)
    ext = Path(rel).suffix
    if ext not in BINARY_KINDS:
        raise Rejected("asset uploads are for .png/.jpg/.jpeg/.webp/.woff2/.mp4; send text files with submit_motion")
    if not 16 <= length <= MAX_ASSET[ext]:
        raise Rejected(f"{ext} assets are limited to {MAX_ASSET[ext] >> 20} MiB")
    if sum(r["bytes"] for r in tree(project)) + length > MAX_TREE:
        raise Rejected("motion folder would exceed 4 GiB; delete unused assets by resubmitting")
    if shutil.disk_usage(project).free < length + int(os.environ.get("VIDEO_DISK_RESERVE_MB", "1024")) * 1024 * 1024:
        raise Rejected("not enough free disk for this asset plus the disk reserve (VIDEO_DISK_RESERVE_MB, default 1 GiB)")
    target = src_dir(project) / rel
    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    tmp = target.with_name(target.name + ".part")
    try:
        with tmp.open("wb") as f:
            remaining, head = length, b""
            while remaining:
                data = stream.read1(min(1 << 16, remaining)) if hasattr(stream, "read1") else stream.read(min(1 << 16, remaining))
                if not data:
                    raise Rejected("truncated asset upload")
                if len(head) < 16:
                    head += data[:16]
                f.write(data)
                remaining -= len(data)
        if not MAGIC[ext](head):
            raise Rejected(f"{rel}: content is not a real {ext} file")
        tmp.replace(target)
    finally:
        tmp.unlink(missing_ok=True)
    return {"path": rel, "bytes": length, "sha256": next(r["sha256"] for r in tree(project) if r["path"] == rel)}


def status(project: Path) -> dict:
    rows = tree(project)
    plan_file = project / "motion" / "plan.json"
    if not rows or not plan_file.is_file():
        return {"submitted": False, "files": rows}
    plan = json.loads(plan_file.read_text())
    return {"submitted": True, "files": rows, "plan": plan, "composition_sha256": tree_hash(rows, plan),
            "beats": len(plan["beats"]), "inserts": len(plan.get("inserts", [])),
            "caption_suppress": len(plan.get("caption_suppress", []))}


def clear(project: Path) -> None:
    shutil.rmtree(project / "motion", ignore_errors=True)


def base_map(edit: dict, plan: dict) -> tuple[list[int], list[dict]]:
    """Per output frame base-frame id: the source frame, or INSERT_BASE + k*STRIDE + i inside an insert window."""
    from fractions import Fraction
    fps = Fraction(str(edit["fps"]))
    ids = list(edit["source_frame_indices"])
    windows = []
    for k, r in enumerate(plan.get("inserts", [])):
        a, b = math.ceil(r["start"] * fps - 1e-9), min(len(ids), math.ceil(r["end"] * fps - 1e-9))
        still = Path(r["asset"]).suffix != ".mp4"
        for i, f in enumerate(range(a, b)):
            ids[f] = INSERT_BASE + k * INSERT_STRIDE + (0 if still else i)
        windows.append({"insert": k, "asset": r["asset"], "first_frame": a, "frames": b - a, "fit": r.get("fit", "cover"),
                        "clip_start_s": float(r.get("clip_start_s", 0)), "still": still, "start": r["start"], "end": r["end"],
                        "reason": r["reason"]})
    return ids, windows


def ledger_js(edit: dict, plan: dict, ids: list[int], canvas) -> str:
    data = {"fps": str(edit["fps"]), "frames": edit["frames"], "duration": edit["duration"], "canvas": list(canvas),
            "baseFrames": ids, "sourceFrames": edit["source_frame_indices"],
            "beats": [{k: b[k] for k in ("start", "end", "caption_treatment")} for b in plan["beats"]],
            "inserts": [{k: r[k] for k in ("start", "end", "asset")} for r in plan.get("inserts", [])],
            "captionSuppress": [{k: r[k] for k in ("start", "end")} for r in plan.get("caption_suppress", [])]}
    return ("/* Generated by DeFleur Video: locked source-frame ledger for James' capture.cjs. Do not edit. */\n"
            "window.DEFLEUR = " + json.dumps(data, separators=(",", ":")) + ";\n"
            "window.sourceFrameForOutputFrame = (frame) => window.DEFLEUR.baseFrames[frame];\n"
            "window.DEFLEUR.inBeat = (t) => window.DEFLEUR.beats.find(b => b.start <= t && t < b.end) || null;\n"
            "window.DEFLEUR.inInsert = (t) => window.DEFLEUR.inserts.find(b => b.start <= t && t < b.end) || null;\n"
            "if (typeof window.captionSuppressed !== 'function') window.captionSuppressed = (t) => "
            "window.DEFLEUR.captionSuppress.some(r => r.start <= t && t < r.end);\n"
            "if (typeof window.visualMode !== 'function') window.visualMode = (t) => window.DEFLEUR.inInsert(t) ? 'fullscreen-insert' : "
            "(window.DEFLEUR.inBeat(t) ? 'beat' : 'live');\n")


def materialize(project: Path, dest: Path) -> dict:
    """Copy the composition into a capture root (hard links where possible)."""
    st = status(project)
    if not st["submitted"]:
        raise Rejected("no motion composition submitted for this project (submit_motion)")
    root = src_dir(project)
    for r in st["files"]:
        target = dest / r["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        try:
            (root / r["path"]).link_to(target) if hasattr(Path, "link_to") else target.hardlink_to(root / r["path"])
        except OSError:
            shutil.copyfile(root / r["path"], target)
    return st
